#!/usr/bin/env bash
# Install and configure Nginx

# Update package lists
apt-get update -y

# Install Nginx
apt-get install nginx -y

# Make sure Nginx is running (without systemctl)
service nginx start

# Replace the default index.html with text containing "Holberton School"
echo "Holberton School for the win!" | tee /var/www/html/index.nginx-debian.html > /dev/null

# Ensure the page contains the required string
echo "Holberton School for the win!" > /var/www/html/index.html
