#!/usr/bin/env bash
# Configures a 301 redirect for /redirect_me

# Install nginx
sudo apt-get update -y
sudo apt-get install -y nginx

# Insert a redirect block directly before the last closing bracket
sudo sed -i '/server_name _;/a \\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}' /etc/nginx/sites-available/default

# Restart nginx
sudo systemctl restart nginx
